baseUrl = "https://llamashoes.github.io"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 5

[params]
contentTypeName = "posts"
themeColor = "black"
showMenuItems = 3
showLanguageSelector = false
fullWidthTheme = false
centerTheme = false

[languages.en]
languageName = "English"
title = "llamshoes"
subtitle = "in the air"
keywords = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "llamashoes"
logoHomeLink = "/"

[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
